### ISSUE TITLE
More info about the cache

### ISSUE THREAD

**Issue by jenstornell** [AugustMiller/kirby-architect#5]
> The plugin implements a static $blueprints property that acts as a cache for parsed Blueprints. Repeated reading and parsing of Blueprints has a major impact on performance.

How does it work? Is it refreshed every time a new blueprint file is used or is it a multilpe array? What is in the cache? The whole blueprint as array?

Reply here or in the docs. I just used my own blueprint repo but with 5 requests it's already noticeable slower (I don't have a cache).

I just want to make sure that I use your repo in a way that the cache is kept and not overwritten. Maybe it's all magic and I don't even need to think about it?

**Comment by AugustMiller** [comment]
The `Architect` class's static `$cache` property is populated per-request. It prevents the `Architect::blueprint` method from having to read Yaml off the disk every time one of the other helper functions requests a blueprint value.

Originally, the plugin was developed for the [Coffee Variety Catalog](https://varieties.worldcoffeeresearch.org/), which outputs dozens of translated blueprint options per page (especially on a [single variety](https://varieties.worldcoffeeresearch.org/varieties/centroamerica)), and it was having to re-read the same file off the disc as many times, _parsing it each time_!

The “cache” allows the server to [read and parse the blueprint _once_ and then refer to it from memory](https://github.com/AugustMiller/kirby-architect/blob/master/architect.php#L7-L11).

The combination of slow disk I/O and reducing the overhead of continually re-parsing hundreds of lines of Yaml brought the TTFB back down from 500–1000ms to a more comfortable (and normal) 50-60ms.

**Comment by AugustMiller** [comment]
I think the other half of this answer are [these lines](https://github.com/AugustMiller/kirby-architect/blob/775eb4976be43e0d71bfc905c58ce33e616434e4/architect.php#L9-L15) from the primary plugin file:

``` php
class Architect {
  # ...
  private static $blueprints = [];

  # Fetch all data for a Blueprint as an associative array
  public static function blueprint ($template) {
    if ( isset(static::$blueprints[$template]) ) {
      return static::$blueprints[$template];
    } else {
      return static::$blueprints[$template] = yaml::decode(kirby()->get('blueprint', $template));
    }
  }
  # ...
}
```

Before reading a blueprint from the disk/registry, we look in the static `$cache` property for a key matching the blueprint's name. If it hasn't been set, we parse the Yaml and save it to that key so it's accessible, later.
