### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by jenstornell** [AugustMiller/kirby-architect#6]
## Cache

Adding many items does not seems to make an extra load time. It seems like the cache is working then?

``` php
echo Architect::blueprint('default')['title'];
echo Architect::blueprint('default')['title'];
echo Architect::blueprint('default')['title'];
echo Architect::blueprint('default')['title'];
```
## Docs

I did not understand the docs right away. Maybe rename `variety` to like `default` to make it more clear? Maybe `density` as well? Ahh, now I see. You are refering to your own example.
## Missing really important features

I need to use it for blueprints registered by a plugin and that does not yet work. It means I can't use it in my project yet. I will not move my blueprints out of my plugin folder.

The same probably goes for registered global field definitions at some point.
## Misc

Else you seems like a more skilled developer than me that also think of most of the little things like blueprint languages etc.

Good job!

**Comment by AugustMiller** [comment]
Appreciate the feedback! I think we've addressed each of these in their respective issues— I'll think on the docs comprehension problem, as it's a valid concern.

If you have a more abstract example blueprint, I'd be glad to consider it!
